[build]
builder = "NIXPACKS"

[deploy]
startCommand = "alembic upgrade head && cd src && uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
